// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
} from "./types";


export default __t.row({
  id: __t.string(),
  name: __t.string(),
  get position() {
    return Vec3;
  },
  radius: __t.f32(),
  thickness: __t.f32(),
  rotation: __t.f32(),
  get inclanation() {
    return __t.option(Vec3);
  },
  morphology: __t.string(),
  primaryColor: __t.string().name("primary_color"),
  secondaryColor: __t.string().name("secondary_color"),
  description: __t.string(),
  discoveredBy: __t.string().name("discovered_by"),
  estimatedSystems: __t.string().name("estimated_systems"),
  seed: __t.f32(),
  armCount: __t.option(__t.u16()).name("arm_count"),
  armWinding: __t.option(__t.f32()).name("arm_winding"),
  companions: __t.option(__t.string()),
  home: __t.option(__t.bool()),
});
