// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CloseInTick = __t.object("CloseInTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CloseInTick = __Infer<typeof CloseInTick>;

export const Galaxy = __t.object("Galaxy", {
  id: __t.string(),
  name: __t.string(),
  get position() {
    return Vec3;
  },
  radius: __t.f32(),
  thickness: __t.f32(),
  rotation: __t.f32(),
  get inclination() {
    return __t.option(Vec3);
  },
  morphology: __t.string(),
  primaryColor: __t.string(),
  secondaryColor: __t.string(),
  description: __t.string(),
  discoveredBy: __t.string(),
  estimatedSystems: __t.string(),
  seed: __t.f32(),
  armCount: __t.option(__t.u16()),
  armWinding: __t.option(__t.f32()),
  companions: __t.option(__t.string()),
  home: __t.option(__t.bool()),
});
export type Galaxy = __Infer<typeof Galaxy>;

export const GameClock = __t.object("GameClock", {
  id: __t.u8(),
  lastTick: __t.timestamp(),
});
export type GameClock = __Infer<typeof GameClock>;

export const Person = __t.object("Person", {
  name: __t.string(),
});
export type Person = __Infer<typeof Person>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  authIssuer: __t.string(),
  authSubject: __t.string(),
  username: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const Vec3 = __t.object("Vec3", {
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
export type Vec3 = __Infer<typeof Vec3>;

