// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3F,
  BlackHole,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  galaxyId: __t.string().name("galaxy_id"),
  name: __t.string(),
  get position() {
    return Vec3F;
  },
  primaryKind: __t.string().name("primary_kind"),
  mapRole: __t.string().name("map_role"),
  spectralType: __t.string().name("spectral_type"),
  starColor: __t.string().name("star_color"),
  starRadius: __t.f32().name("star_radius"),
  get blackHole() {
    return __t.option(BlackHole).name("black_hole");
  },
  zoneColor: __t.option(__t.string()).name("zone_color"),
  zoneRadius: __t.option(__t.f32()).name("zone_radius"),
  zoneStrength: __t.option(__t.f32()).name("zone_strength"),
  zoneName: __t.option(__t.string()).name("zone_name"),
  ownerIdentity: __t.option(__t.identity()).name("owner_identity"),
  description: __t.string(),
  faction: __t.string(),
  population: __t.u64(),
});
