// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  planetId: __t.string().name("planet_id"),
  name: __t.string(),
  moonType: __t.string().name("moon_type"),
  radius: __t.f32(),
  orbitRadius: __t.f32().name("orbit_radius"),
  orbitSpeed: __t.f32().name("orbit_speed"),
  orbitOffset: __t.f32().name("orbit_offset"),
  orbitInclination: __t.f32().name("orbit_inclination"),
  orbitEccentricity: __t.f32().name("orbit_eccentricity"),
  orbitLongitude: __t.f32().name("orbit_longitude"),
  orbitArgument: __t.f32().name("orbit_argument"),
  color: __t.string(),
  secondaryColor: __t.option(__t.string()).name("secondary_color"),
});
