// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlanetTemperature,
  PlanetProduction,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  systemId: __t.string().name("system_id"),
  name: __t.string(),
  planetType: __t.string().name("planet_type"),
  radius: __t.f32(),
  orbitRadius: __t.f32().name("orbit_radius"),
  orbitSpeed: __t.f32().name("orbit_speed"),
  orbitOffset: __t.f32().name("orbit_offset"),
  orbitInclination: __t.f32().name("orbit_inclination"),
  orbitEccentricity: __t.f32().name("orbit_eccentricity"),
  orbitLongitude: __t.f32().name("orbit_longitude"),
  orbitArgument: __t.f32().name("orbit_argument"),
  orbitIndex: __t.u16().name("orbit_index"),
  color: __t.string(),
  secondaryColor: __t.option(__t.string()).name("secondary_color"),
  get temperature() {
    return PlanetTemperature;
  },
  population: __t.u64(),
  colonized: __t.bool(),
  get production() {
    return __t.option(PlanetProduction);
  },
  gravity: __t.f32(),
  atmosphere: __t.string(),
  description: __t.string(),
  discoveredBy: __t.string().name("discovered_by"),
  resources: __t.array(__t.string()),
  axialTilt: __t.f32().name("axial_tilt"),
  tidallyLocked: __t.bool().name("tidally_locked"),
  landFraction: __t.option(__t.f32()).name("land_fraction"),
  ringColor: __t.option(__t.string()).name("ring_color"),
});
