// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as CountProcedure from "../count_procedure";

export type CountArgs = __Infer<typeof CountProcedure.params>;
export type CountResult = __Infer<typeof CountProcedure.returnType>;

